### ISSUE TITLE
同時使用折價券+88折扣時，開立發票出現錯誤

### ISSUE THREAD

**Issue by andykao1026** [j7-dev/woomp#19]
綠界開發票也會有一樣的狀況

**Comment by j7-dev** [comment]
## 問題描述

3件商品總金額917
無法被整除，引發發票開立錯誤

![image](https://github.com/j7-dev/woomp/assets/9213776/778ec11f-6b0d-4037-80f6-d400abdcaf70)

![image](https://github.com/j7-dev/woomp/assets/9213776/057ec41c-ce79-4fd5-b242-962b71147354)

## 解法

[參考綠界文件](https://developers.ecpay.com.tw/?p=15369)

![image](https://github.com/j7-dev/woomp/assets/9213776/757a6b37-9901-45da-9d5d-c734dcba29a7)
![image](https://github.com/j7-dev/woomp/assets/9213776/77ac5a44-ea5c-4e0e-b353-d99fb3f862f5)

將有小數點限制的參數改用 `number_format` 包起來就好
![image](https://github.com/j7-dev/woomp/assets/9213776/9939879c-98b7-4321-b0c4-7a5c20d72445)


## 同場加映: 發票明明錯誤，卻顯示開立成功
這個順便改了  之前小賴的作法
只要發票有成功送出  是不管綠界回啥，一律回成功@@

現在改成  會回綠界回的訊息  ex 格是錯誤

**Comment by j7-dev** [comment]
經過線上測試後，還是有錯誤
單價計算錯誤，變成1 * 0.33 = 1元了  單價完全錯誤
![image](https://github.com/j7-dev/woomp/assets/9213776/c479500b-6d37-4f95-ab16-5538b5ba38bc)


判斷是商品資訊那邊寫錯
![image](https://github.com/j7-dev/woomp/assets/9213776/43345138-022b-4c63-90b6-825f8c30a2ef)


$itemsTmp = $order->get_items();
$itemsTmp 會變成一個 `WC_Order_Item_Product` 物件組成的 array
然後遍歷出來

```
[14-Nov-2023 04:41:11 UTC] ⭐ 一些數據 Array
(
    [get_quantity] => 3
    [get_subtotal] => 1197
    [get_subtotal_tax] => 0
    [get_total] => 917
    [get_total_tax] => 0
)
```

**Comment by j7-dev** [comment]
原本寫法完全是在瞎寫
用陣列的拿法去拿物件的屬性，居然不會出錯也是奇蹟了

![image](https://github.com/j7-dev/woomp/assets/9213776/bcd13c9b-57a6-4fc5-8757-0755d8fde76e)

**Comment by andykao1026** [comment]
錯誤已排除
