### ISSUE TITLE
同時使用折價券+88折扣時，開立發票出現錯誤

### ISSUE THREAD

**Issue by andykao1026** [j7-dev/woomp#3]
以下狀況可正常開立發票
1、單獨使用折價券，或是單獨使用88折的時候，可以正常開立發票
2、當此商品數量1、2、4、5、7的數量時，以及同時使用折價券+88折扣時，可以正常開立發票
https://yuxintw.hopesmarketing.tw/product/alyssana-果酸一點靈高效修護護髮素150ml/

以下狀況開立發票發生錯誤
1、當此商品數量在3、6的數量時，以及同時使用折價券+88折扣時，開立發票出現錯誤
https://yuxintw.hopesmarketing.tw/product/alyssana-果酸一點靈高效修護護髮素150ml/

錯誤訊息:
發票開立失敗
回傳訊息: 商品價格格式錯誤(第1列)

電子發票LOG沒有出現錯誤訊息

**Comment by j7-dev** [comment]
![圖片](https://github.com/j7-dev/woomp/assets/9213776/92036947-fbc0-4a75-af35-3fa21736be5c)

**Comment by j7-dev** [comment]
![圖片](https://github.com/j7-dev/woomp/assets/9213776/2cbcdb46-cb30-41af-923f-db81d18faf5a)

![圖片](https://github.com/j7-dev/woomp/assets/9213776/690cbd71-e9da-42ea-8205-4c0b6f2442c6)

**Comment by j7-dev** [comment]
問題發生在
`wp-content\plugins\woomp\includes\paynow-einvoice\includes\class-paynow-einvoice.php`

![圖片](https://github.com/j7-dev/woomp/assets/9213776/2a45ad02-9533-4909-bfef-f92ff5721507)

**Comment by andykao1026** [comment]
綠界的發票也是一樣的狀況
