### ISSUE TITLE
[統一金] 啟用 3D 驗證後重複授權的問題

### ISSUE THREAD

**Issue by j7-dev** [j7-dev/woomp#31]
啟用3D驗證後，使用統一金信用卡付款
後台備註會顯示2次授權成功

![image](https://github.com/j7-dev/woomp/assets/9213776/14583a97-b38e-4b46-ae45-b30589bcfe0f)

**Comment by j7-dev** [comment]
## 原因

![image](https://github.com/j7-dev/woomp/assets/9213776/45ba8e4e-d2fb-4766-a7d5-b8313a61fa52)

![image](https://github.com/j7-dev/woomp/assets/9213776/c0a748d3-9d89-4598-9bd5-a8e1f72a0825)


## 解法

將 `$data['ReturnURL']` 改調就可以，暫定改為首頁

**Comment by ucheng** [comment]
NotifyURL 一定要帶喔，因為交易狀態有更新都是透過 NotifyURL 回傳。
在3D驗證啟用的狀態下，交易會另外帶 ReturnURL 的參數，讓完成 3D 驗證後可以導向指定的網址。
網站會透過 ReturnURL 和 NotifyURL 收到統一金流的回傳，所以這個 issue 並不是重複授權，而是收到 ReturnURL 和 NotifyURL 的回傳後都寫入到訂單備註了，所以會讓人以為是重複授權。
