### ISSUE TITLE
定期定額授權金額不同

### ISSUE THREAD

**Issue by j7-dev** [j7-dev/woomp#4]
訂單是$100，但統一金流只有授權$5

訂單#26

https://staging1.luke.cafe/wp-admin/post.php?post=26&action=edit

![image](https://github.com/j7-dev/woomp/assets/9213776/c034d1d2-ea9a-41e9-a5fb-398e208e0872)

![image](https://github.com/j7-dev/woomp/assets/9213776/f6146bc1-953d-4338-b94e-022b0d896ec8)

**Comment by lukehsuhao** [comment]
這個主要的部分已解決，延伸出一個問題是

試用期扣款的5元，目前不會自動退款，需要加入自動退款的機制

另外，現在每次在訂閱的裡面，更改下次扣款的日期，就會觸發扣5元，這個不需要觸發才對，只有首次開啟訂閱時需要觸發那個
