### ISSUE TITLE
切換訂閱方案時，無顯示任何付款方式

### ISSUE THREAD

**Issue by Ck-Joker** [j7-dev/woomp#47]
使用Woo Subscription外掛時，使用「切換訂閱方案」功能後，無法正常結帳，故無法完成切換訂閱之功能

![image](https://github.com/j7-dev/woomp/assets/132816301/ed3cfedb-408f-4fef-8483-bdca7864c163)

https://github.com/j7-dev/woomp/assets/132816301/7680931f-3c6d-454e-849b-a9c3a297776a

**Comment by j7-dev** [comment]
其實是錯在 woocommerce-memberships

>Error: Unknown format specifier "�",File: /home/movethink/htdocs/movethink.org/wp-content/plugins/woocommerce-memberships/src/class-wc-memberships-membership-plan.php Line: 2040

是因為翻譯導致 `sprintf` 的錯誤

![圖片](https://github.com/j7-dev/woomp/assets/9213776/cc2d2b99-7d37-48a6-8e2b-2ed7fa1c430a)
